- name: copy libvirt-usb udev rules
  command: cp /tmp/libvirt-usb/60-usb-libvirt.rules /etc/udev/rules.d/60-usb-libvirt.rules
  listen: cloned_libvirt_usb

- name: copy libvirt-usb shell script
  command: cp /tmp/libvirt-usb/libvirt-usb.sh /etc/libvirt/libvirt-usb.sh
  listen: cloned_libvirt_usb

- name: chmod libvirt-usb shell script
  file:
    path: /etc/libvirt/libvirt-usb.sh
    mode: o+x
  listen: cloned_libvirt_usb
