- import_tasks: selinux.yml
- import_tasks: containers.yml
- import_tasks: libvirt.yml
- import_tasks: libvirt-usb.yml
- import_tasks: pulseaudio.yml
- import_tasks: ssh.yml
- import_tasks: firewall.yml

- name: rebuild grub
  command: grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
