- name: copy podman folders
  copy:
    src: files/podman/
    dest: /tmp/podman/
  notify: new_container_images

- name: copy dnsmasq template
  template:
    src: dnsmasq.conf.j2
    dest: /tmp/podman/dnsmasq.conf
  notify: new_container_images

- name: copy hostpad template
  template:
    src: hostapd.conf.j2
    dest: /tmp/podman/hostapd.conf
  notify: new_container_images


