- name: move external_interface to external zone
  command: "firewall-cmd --zone=external --permanent --add-interface={{external_interface}}"

- name: openssh disabled on external zone
  command: firewall-cmd --zone=external --permanent --remove-service=ssh

- name: move internal_interface to internal  zone
  command: "firewall-cmd --zone=internal --permanent --add-interface={{internal_interface}}"

- name: dhcp enabled on internal zone
  command: firewall-cmd --zone=internal --permanent --add-service=dhcp

- name: dns enabled on internal zone
  command: firewall-cmd --zone=internal --permanent --add-service=dns

- name: dns rejected to others on udp from internal
  command: "firewall-cmd --zone=internal --permanent --direct --add-rule ipv4 filter FORWARD 0 -s {{internal_net}} -p udp -m udp --dport=53 -j REJECT"

- name: dns rejected to others on tcp from internal
  command: "firewall-cmd --zone=internal --permanent --direct --add-rule ipv4 filter FORWARD 0 -s {{internal_net}} -p tcp -m tcp --dport=53 -j REJECT"


