- name: enable ssh authkey authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#PubkeyAuthentication yes'
    line: 'PubkeyAuthentication yes'

- name: disable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^PasswordAuthentication yes'
    line: 'PasswordAuthentication no'

- name: disable ssh root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^PermitRootLogin yes'
    line: 'PermitRootLogin no'

- name: ipv4 only
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#AddressFamily any'
    line: 'AddressFamily inet'

- name: listen on internal address only
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#ListenAddress 0.0.0.0'
    line: 'ListenAddress 10.10.10.1'

- name: reload ssh
  systemd:
    name: sshd
    state: restarted


